### ISSUE TITLE
note-range package status

### ISSUE THREAD

**Issue by devboell** [danigb/tonal#4]
Hi there,

  I was wondering about the note-range package. It appears it is not part of the current npm install of tonal and has the 'npm invalid' tag. Will it be included in a next release, or is there another way I can use it?

  thanks

**Comment by danigb** [comment]
Hi,

I'm working hard on next version of tonal (0.50.x series) that I hope will be release at the end of next week. It will include note-range by default. Meanwhile, the only option is to clone this repo and install the package manually:

```
npm install ../path-to-tonal/packages/note-range
```

Cheers,
Dani

**Comment by devboell** [comment]
Good to hear a new version is coming soon!
  I think I have a workaround for now, but I have a question on how you will be handling enharmonics for chromatic scales. My use case is that I want to generate a noteMatrix representing a guitar fretboard, based on a tuning. So, roughly my code is this:

```
const defaultTuning = List(['e3', 'a3', 'd4', 'g4', 'b4', 'e5'])
const SCALE = '1 2b 2 3b 3 4 4# 5 6b 6 7b 7'.split(' ')

const noteMatrix = (tuning = defaultTuning) => {
  const matrix = []
  for (const note of tuning) {
    const string = []
    string.push(tonal.scale(SCALE, note))
    string.push(tonal.transpose(note, 'P8'))
    matrix.push(List(string));
  }
  return List(matrix)
}
```

This results f.i. in that a raised A3 on the sixth string will be A#3, but on the fifth string Bb3, because for each string the scale method uses a different tonic. But when I render the fretboard I want them both to display "A#3 / Bb3" (and this for all 'simple' enharmonics)
  I will write a formatting method to handle this, but I am curious for your thoughts on this.

  thanks a lot,
Rob

**Comment by danigb** [comment]
Hi Rob, this is an interesting use case. Currently I'm outside for three days, but I will think about it, and propose some solutions as soon I'm back. 👍

**Comment by danigb** [comment]
Hi Rob, 

I'm back. I assume that you want to display the same scale over the fretboard. The problem with your example is that you are creating a different scale for each string (the same intervals, but with different tonic: different scale). What you need, in fact, is note-range. With note-range you can specify an scale and a first and last note and you will get that scale between that notes. The idea is to apply same scale to different note ranges. If you find useful, I don't mind to implement a tonal-fretboard module that help with that tasks.

**Comment by devboell** [comment]
Hi Dani,

  Thanks for coming back to this. I agree using note-range would be the cleanest solution, so I'll just wait until you are ready with the next release. I don't think a special tonal-fretboard module is necessary, although I am unclear if the current version of note-range already supports the behaviour you describe (on the current master-branch I see ``` range(scale, tonic, length) ```. 

I think I would need something like this:
``` range(scale, tonic, startnote, endnote)```
or:
``` range(scale, tonic, startnote, length)```

with either of these methods my use case would be adequately covered.

Cheers,
Rob

ps:  It seems some of the examples in note-range aren't correct. I couldn't understand these two:
```
range('1 2 3 4 5 6 7', 'A2', 5) // => ['A2', 'C#3', 'E3', 'A3', 'C#4']
range('1 3 5', 'A2', -5) // => ['A2', 'E3', 'C#3', 'A1', 'E0']
```

**Comment by danigb** [comment]
Hi Rob,

The next iteration of tonal is being developed in the 0.50.x branch. Currently the scaleRange function is implemented at the bottom of: https://github.com/danigb/tonal/blob/tonal-0.50.x/packages/tonal-scales/lib/index.js (but I'm not sure if this is going to be the definitive place). The test are here: https://github.com/danigb/tonal/blob/tonal-0.50.x/packages/tonal-scales/test/scale-range-test.js

As you can see the signaure is what you expect:

```scaleRange(scale|scaleName, startnote, endnote)```

Thanks for pointing the problems with note-range module. I re-implemented the range related functions from scratch and I hope they are solved. Anyway I will look carefully to them.

Cheers,
Dani

**Comment by devboell** [comment]
Aha, that looks very good!

 Thanks a lot Dani, and good luck with the release!

**Comment by danigb** [comment]
Thanks Rob. Latest update: range related methods finally has its own module (again): https://github.com/danigb/tonal/tree/tonal-0.50.x/packages/tonal-ranges

You can read the API here: https://github.com/danigb/tonal/blob/tonal-0.50.x/packages/tonal-ranges/API.md

**Comment by devboell** [comment]
cool, I also noticed the ```chromatic(...)``` method, which is very handy. I cloned the 0.50 branch on my machine, and tried to play with it, but I ran into some installation problems. This could well be because I am not installing correctly, or just because the branch-repo is in flux at the moment.
  So, I still have a couple of questions, but since you're working on the release, I'm not sure if this the right time to raise them.

**Comment by danigb** [comment]
Great! This is the perfect time to raise them. Cheers, Dani

**Comment by devboell** [comment]
ok, then first about the installation, I opened a separate issue, please have look.

**Comment by danigb** [comment]
Hi again,

The first of 0.50.x series is released with tonal-range included and enhanced. As you can test, you can pass several notes to create comples ranges: `tonal.range('C2 C4 E3') => ['C2' ... 'C4' ... 'E3']`

I'm closing this issue but please reopen if you have any problem or question.
